# Generated by Django 3.2.7 on 2023-07-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211231_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Isadmin',
            field=models.BooleanField(default=False),
        ),
    ]
