# Generated by Django 3.2.7 on 2021-12-22 05:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmanagermaster',
            name='UpdateDate',
        ),
        migrations.RemoveField(
            model_name='projectmanagermaster',
            name='UpdatedBy',
        ),
        migrations.AddField(
            model_name='categorymaster',
            name='DeleteFlag',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='categorymaster',
            name='DeletedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorymaster',
            name='DeletedOn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='categorymaster',
            name='submittedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorymaster',
            name='submittedDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 22, 5, 48, 40, 720039, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divisionmaster',
            name='Abbr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='divisionmaster',
            name='DeleteFlag',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='divisionmaster',
            name='DeletedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='divisionmaster',
            name='DeletedOn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='divisionmaster',
            name='submittedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='divisionmaster',
            name='submittedDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 22, 5, 48, 49, 704559, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmanagermaster',
            name='DeleteFlag',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='projectmanagermaster',
            name='DeletedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmanagermaster',
            name='DeletedOn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='projectmanagermaster',
            name='submittedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmanagermaster',
            name='submittedDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 22, 5, 48, 52, 188974, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regionmaster',
            name='Abbr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='regionmaster',
            name='DeleteFlag',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='regionmaster',
            name='DeletedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regionmaster',
            name='DeletedOn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='regionmaster',
            name='submittedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regionmaster',
            name='submittedDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 22, 5, 48, 54, 392133, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
