# Generated by Django 3.2.7 on 2022-03-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_auto_20211222_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanagermaster',
            name='BUHead',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
