from django.db import models
from users.models import User


class proformaItemMaster(models.Model):
    ProformaID = models.AutoField(primary_key=True, unique=True)
    DocNo = models.IntegerField(null=True, blank=True)
    DocDate = models.DateField(null=True)
    Supplier = models.CharField(null=True, max_length=1000)
    SupTelephone = models.CharField(null=True, max_length=255)
    Website = models.CharField(null=True, max_length=255)
    SoldtoCode = models.CharField(null=True, max_length=255)
    SoldToAddress = models.CharField(null=True, max_length=1000)
    Shiptocode = models.CharField(null=True, max_length=255)
    Shiptoaddress = models.CharField(null=True, max_length=1000)
    EndUserCode = models.CharField(null=True, max_length=255)
    EndUserAddress = models.CharField(null=True, max_length=1000)
    Billtocode = models.CharField(null=True, max_length=255)
    Billtoaddress = models.CharField(null=True, max_length=1000)
    CusRefDesc = models.CharField(null=True, max_length=255)
    CusDeliverydate = models.DateField(null=True)
    Incoterms = models.CharField(null=True, max_length=255)
    SalesOffice = models.CharField(null=True, max_length=255)
    YilContactperson = models.CharField(null=True, max_length=255)
    Approver = models.CharField(null=True, max_length=255)
    Section = models.CharField(null=True, max_length=255)
    Email = models.CharField(null=True, max_length=255)
    Telephone = models.CharField(null=True, max_length=255)
    PONo = models.CharField(null=True, max_length=255)
    PoDate = models.DateField(null=True)
    IndentNo = models.CharField(null=True, max_length=255)
    Remarks = models.CharField(null=True, max_length=255)
    PaymentTerms = models.CharField(null=True, max_length=1000)
    DocrefNo = models.CharField(null=True, max_length=255)
    TotalItemvalue = models.FloatField(default=0.00, null=True)
    SubmittedDate = models.DateTimeField(auto_now_add=True, null=True)
    Advance = models.FloatField(default=0.00, null=True)
    Retention = models.FloatField(default=0.00, null=True)
    FreightLumSum = models.FloatField(default=0.00, null=True)
    GSTType = models.CharField(null=True, max_length=255)
    CurrencyType = models.CharField(null=True, max_length=255)
    UpdatedDate = models.DateTimeField(auto_now=True)

    SubmittedBy = models.ForeignKey(User, related_name='+', null=True, on_delete=models.CASCADE)
    UpdatedBy = models.ForeignKey(User, related_name='+', null=True, on_delete=models.CASCADE)
    DeleteFlag = models.BooleanField(null=True)
    DeletedBy = models.IntegerField(null=True, blank=True)
    DeletedSono = models.IntegerField(null=True, blank=True)

    objects = models.Manager()


class proformaItem(models.Model):
    ProformaItemid = models.AutoField(primary_key=True, unique=True)
    ProformaID = models.ForeignKey(proformaItemMaster, related_name='items', null=True, blank=True, on_delete=models.CASCADE)
    OAItemNo = models.IntegerField(null=True, blank=True)
    ItemNo = models.IntegerField(null=True, blank=True)
    MaterialDesc = models.CharField(null=True, max_length=255)
##    Qtymodels = models.IntegerField(null=True, blank=True)
    Qtymodels = models.FloatField(default=0.00, null=True, blank=True)
    UOM = models.CharField(null=True, max_length=255)
    UnitPrice = models.FloatField(default=0.00, null=True)
    UnitType = models.CharField(null=True, max_length=255)
    TotalPrice = models.FloatField(default=0.00, null=True)
    TotalType = models.CharField(null=True, max_length=255)
    PartName = models.CharField(null=True, max_length=255)
    CusPartNo = models.CharField(null=True, max_length=255)
    CusPartSlno = models.CharField(null=True, max_length=255)
    HSN = models.IntegerField(null=True, blank=True)
    DiscountPercent = models.FloatField(default=0.00, null=True)
    DiscountAmount = models.FloatField(default=0.00, null=True)
    ItemValuewithDiscount = models.FloatField(default=0.00, null=True)
    PFpercent = models.FloatField(default=0.00, null=True)
    PFAmount = models.FloatField(default=0.00, null=True)
    FreightPercent = models.FloatField(default=0.00, null=True)
    FreightAmount = models.FloatField(default=0.00, null=True)
    MatReadyDate = models.DateTimeField(null=True)
    ItemValuewithPF = models.FloatField(default=0.00, null=True)
    SGSTpercent = models.FloatField(default=0.00, null=True)
    SGSTAmount = models.FloatField(default=0.00, null=True)
    CGSTPercent = models.FloatField(default=0.00, null=True)
    CGSTAmount = models.FloatField(default=0.00, null=True)
    IGSTPercent = models.FloatField(default=0.00, null=True)
    IGSTAmount = models.FloatField(default=0.00, null=True)
    ItemValuewithGST = models.FloatField(default=0.00, null=True)
    SubmittedDate = models.DateTimeField(auto_now_add=True, null=True)

    SubmittedBy = models.ForeignKey(User, related_name='+', null=True, on_delete=models.CASCADE)
    DeleteFlag = models.BooleanField(null=True)
    DeletedBy = models.ForeignKey(User, related_name='+', null=True, on_delete=models.CASCADE)

    objects = models.Manager()


