# Generated by Django 3.2.7 on 2021-12-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelupload', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformaitemmaster',
            name='Billtoaddress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proformaitemmaster',
            name='Billtocode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
