# Generated by Django 3.2.7 on 2022-01-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelupload', '0004_alter_proformaitemmaster_paymentterms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformaitemmaster',
            name='Billtoaddress',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='proformaitemmaster',
            name='EndUserAddress',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='proformaitemmaster',
            name='PaymentTerms',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='proformaitemmaster',
            name='Shiptoaddress',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='proformaitemmaster',
            name='SoldToAddress',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='proformaitemmaster',
            name='Supplier',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
