# Generated by Django 3.2.7 on 2022-08-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelupload', '0005_auto_20220127_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformaitem',
            name='Qtymodels',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
