# Generated by Django 3.2.7 on 2023-03-16 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orderack', '0001_initial'),
        ('excelupload', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderacknowledgementhistory',
            name='DeletedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderacknowledgementhistory',
            name='OrderAckId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orderack.orderacknowledgement'),
        ),
        migrations.AddField(
            model_name='orderacknowledgementhistory',
            name='SubmittedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderacknowledgementhistory',
            name='UpdatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderacknowledgement',
            name='DeletedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderacknowledgement',
            name='ProformaID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excelupload.proformaitemmaster'),
        ),
        migrations.AddField(
            model_name='orderacknowledgement',
            name='SubmittedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderacknowledgement',
            name='UpdatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
