# Generated by Django 3.2.7 on 2021-12-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderack', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderacknowledgement',
            name='JobCode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
