# Generated by Django 3.2.7 on 2021-12-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderack', '0003_alter_orderacknowledgement_jobcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderacknowledgement',
            name='PI_CODE',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderacknowledgement',
            name='PI_NO',
            field=models.IntegerField(null=True),
        ),
    ]
