# Generated by Django 3.2.7 on 2021-12-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderack', '0004_auto_20211222_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderacknowledgementhistory',
            name='PartName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
