# Generated by Django 3.2.7 on 2022-07-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderack', '0006_auto_20220428_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderacknowledgementhistory',
            name='APBGDetails',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orderacknowledgementhistory',
            name='Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orderacknowledgementhistory',
            name='PaymentTerms',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orderacknowledgementhistory',
            name='PercentonAmt',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
