# Generated by Django 3.2.7 on 2022-08-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderack', '0007_auto_20220725_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderacknowledgementhistory',
            name='PI_Qty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='orderacknowledgementhistory',
            name='Qty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
